export const ADMIN_TEXTS = {
  "admin-panel-title": `🤖 <b>PlayPhoto 2.0 Admin Panel</b>`,
  "admin-panel-team": (p: { active: string | number }) => `👥 <b>Team:</b> ${p.active} active`,
  "admin-panel-locations": (p: { active: string | number }) => `📍 <b>Locations:</b> ${p.active} active`,
  "admin-panel-category": `Choose category:`,
  "support-panel-title": `<b>🛠 Support Panel</b>`,
  "support-panel-tickets": (p: { open: string | number, inprogress: string | number }) => `🎫 <b>Tickets:</b> ${p.open} open / ${p.inprogress} in progress`,
  "support-panel-urgent": (p: { urgent: string | number }) => `🆘 <b>Urgent:</b> ${p.urgent}`,
  "support-panel-tasks": (p: { overdue: string | number }) => `🔴 <b>Tasks:</b> ${p.overdue} overdue`,
  "support-panel-action": `Choose action:`,
  "admin-ops-search": `🔍 Candidate Search`,
  "admin-ops-locations": `📍 Locations`,
  "admin-ops-interviews": `🗓️ Interviews`,
  "admin-ops-staging": (p: { count: string | number }) => `📸 Staging (${p.count})`,
  "admin-ops-stats": `📊 Statistics`,
  "admin-ops-back": `⬅️ Back`,
  "admin-history-only-super": `⚠️ Super Admin only.`,
  "admin-history-no-selection": `⚠️ No user selected.`,
  "admin-history-user-not-found": `❌ User not found.`,
  "admin-history-empty": `📭 Chat history is empty.`,
  "admin-history-caption": (p: { name: string | number, count: string | number }) => `📋 Chat History: ${p.name} (${p.count} records)`,
  "admin-main-team": `👥 Team`,
  "admin-main-hr": `🚀 HR Hub`,
  "admin-main-finance": `💰 Finance`,
  "admin-main-system": `⚙️ System`,
  "admin-header-role": (p: { role: string | number }) => `👤 Role: ${p.role}`,
  "admin-header-balance": (p: { balance: string | number }) => `💰 Balance: ${p.balance} UAH`,
  "admin-btn-refresh": `🔄 Refresh`,
  "admin-btn-home": `🏠 Menu`,
  "admin-btn-back": `⬅️ Back`,
  "admin-btn-cancel": `❌ Cancel`,
  "admin-err-access-denied": `⛔️ Access denied (Main Admin only)`,
  "admin-staging-candidate-not-found": `Candidate not found.`,
  "admin-ans-gen-report": `⏳ Generating report...`,
  "admin-ans-success-hired": `Success! Photographer hired.`,
  "admin-btn-main-menu": `🏠 Menu`,
  "admin-btn-back-to-cities": `⬅️ Back to Cities`,
  "admin-msg-success": `✅ Message sent and logged.`,
  "admin-msg-err-delivery": `❌ Send Error: bot blocked or invalid ID.`,
  "admin-notif-interview-completed": (p: { name: string | number }) => `🏁 <b>Interview Completed: ${p.name}</b>\n\nTime is up, status updated to "Completed". Please review the profile and make an offer decision! ⚖️🌸`,
  "admin-notif-training-completed": (p: { name: string | number }) => `🏁 <b>Training Completed: ${p.name}</b>\n\nSlot time is up. Please mark the result (Passed/Failed) in the candidate's profile so they can proceed to NDA and test! 🎓🌸`,
  "admin-notif-new-onboarding": (p: { name: string | number }) => `🚀 <b>New Onboarding!</b>\n\nCandidate <b>${p.name}</b> has successfully completed all stages and been added to the schedule. 📸\n\nPlease monitor their first shift and assist with adaptation! ✨`,
  "admin-notif-delivery-failed": (p: { name: string | number, error: string | number }) => `⚠️ <b>Offer not delivered!</b>\n\nCandidate: <b>${p.name}</b>\nError: ${p.error}\nCandidate might have blocked the bot. Please contact them manually.`,
  "admin-search-staff-not-found": `Staff not found.`,
  "admin-search-cand-prompt": `Enter Name, Surname or Username to search: 🔍`,
  "admin-search-staff-prompt": `Enter Name or Surname to search: 🔍`,
  "admin-search-no-results": `No results. 😔`,
  "admin-search-no-name": `Unnamed`,
  "admin-staging-title": `📸 <b>Offline Staging</b>`,
  "admin-staging-select": `Select candidate to assign staging:`,
  "admin-staging-none": `No candidates for staging 🌸`,
  "admin-staging-details-date": `📅 Set Staging Date`,
  "admin-staging-details-date-confirm": `📅 Confirm/Change Date`,
  "admin-staging-details-partner": `👩‍💼 Choose Partner`,
  "admin-staging-details-back": `⬅️ Back`,
  "admin-staging-ask-date": `Enter staging date (DD.MM.YYYY):`,
  "admin-staging-partner-title": `👩‍💼 <b>Partner Selection</b>`,
  "admin-staging-partner-loc": (p: { location: string | number }) => `Location: <b>${p.location}</b>`,
  "admin-staging-partner-none": `No active photographers on location ❌`,
  "admin-staging-ans-partner-ok": (p: { name: string | number }) => `Partner assigned: ${p.name} ✅`,
  "admin-staging-ans-assigned": (p: { name: string | number }) => `✅ <b>Assigned!</b>\n\nPartner: ${p.name}\nBoth notified.`,
  "admin-staging-select-loc-title": `📍 <b>Select Staging Location:</b>`,
  "admin-staging-select-loc-hint": `(May differ from candidate preference)`,
  "admin-staging-select-loc-filter-hint": `📍 <b>Select Location:</b>`,
  "admin-staging-details-time": (p: { time: string | number }) => `⏰ Time: ${p.time}`,
  "admin-staging-details-loc": (p: { loc: string | number }) => `📍 Place: ${p.loc}`,
  "admin-staging-ask-custom-time": `✍️ <b>Enter custom time:</b>\nExample: 12:00-14:30`,
  "admin-staging-err-select-loc": `Select location first! 📍`,
  "admin-staging-success-title": `✅ <b>Success!</b>`,
  "admin-staging-success-msg": (p: { partner: string | number, candidate: string | number, time: string | number, location: string | number }) => `<b>${p.partner}</b> assigned as partner for <b>${p.candidate}</b> at ${p.time} in ${p.location}.`,
  "admin-staging-partner-active-title": `✨ Photographers with shifts today:`,
  "admin-staging-partner-none-assigned": `No location selected ❌`,
  "admin-staging-back-btn": `⬅️ Back`,
  "admin-staging-active-none": `No active staging 🌸`,
  "admin-staging-ready-none": `No one waiting for schedule ✨`,
  "admin-staging-label-unassigned": (p: { count: string | number }) => `🆕 Unassigned (${p.count})`,
  "admin-staging-label-active": (p: { count: string | number }) => `⌛ Active (${p.count})`,
  "admin-staging-label-ready": (p: { count: string | number }) => `📋 Ready (${p.count})`,
  "admin-staging-header-active": `⌛ <b>Active Staging</b>\nSelect candidate to record results:`,
  "admin-staging-header-ready": `📋 <b>Waiting for Schedule</b>\nSelect candidate to finalize hiring:`,
  "admin-staging-unnamed": `Unnamed`,
  "admin-staging-card-location": (p: { loc: string | number }) => `📍 Location: ${p.loc}`,
  "admin-staging-card-partner": (p: { partner: string | number }) => `📸 Partner: ${p.partner}`,
  "admin-staging-card-result": `Staging result:`,
  "admin-staging-card-status-pass": `✅ Passed`,
  "admin-staging-card-status-docs": `📝 Documents received`,
  "admin-staging-card-final-step": `Final step: confirm that the schedule is created.`,
  "admin-btn-schedule-created": `✅ Schedule Created`,
  "admin-ans-success-notified": `Success recorded! Candidate notified.`,
  "admin-ans-offer-sent-now": `Offer sent NOW ✅`,
  "admin-ans-accepted": `Decision: ACCEPTED. Offer in 6 hours. ✅`,
  "admin-ans-rejected": `Decision: REJECTED. ❌`,
  "admin-ans-status-updated-success": `Status updated: Success! 🎉`,
  "admin-ans-already-processing": `Request already processing... ⏳`,
  "admin-ans-mentor-notified": `Done! Mentor notified. 🚀`,
  "admin-btn-accept-offer": `🎉 Accept (Offer)`,
  "admin-btn-reject": `❌ Reject`,
  "admin-btn-write-message": `✍️ Message`,
  "admin-btn-send-offer-now": `⚡️ Send NOW`,
  "admin-btn-pass": `✅ Pass`,
  "admin-btn-fail": `❌ Fail`,
  "admin-btn-start-nda": `📑 Start NDA`,
  "admin-btn-schedule-ready": `✅ Schedule Ready`,
  "admin-btn-choose-time": `🗓️ Choose Time`,
  "admin-btn-invite-individual": `📩 Invite to Interview`,
  "admin-btn-yes-send-all": `✅ Yes, Send All`,
  "admin-btn-assign-time": `🗓️ Schedule`,
  "admin-btn-reply": `✍️ Reply`,
  "admin-btn-add-time": `➕ Add Time`,
  "admin-profile-select-action": `Select action:`,
  "admin-profile-btn-msg": `✉️ Write Message`,
  "admin-profile-section-basics": `👤 <b>PROFILE</b>`,
  "admin-profile-section-selection": `⚖️ <b>RECRUITMENT</b>`,
  "admin-profile-section-training": `🎓 <b>TRAINING</b>`,
  "admin-profile-section-current": `🎯 <b>CURRENT STAGE</b>`,
  "admin-profile-materials": `📚 Materials:`,
  "admin-profile-test-passed": `📝 Test:`,
  "admin-profile-status-sent": `Sent 📩`,
  "admin-profile-status-not-sent": `Not sent ⏳`,
  "admin-profile-status-passed": `Passed ✅`,
  "admin-profile-status-waiting": `Waiting ⏳`,
  "admin-profile-title-self": `📸 <b>Your Profile</b>`,
  "admin-profile-title-other": `📸 <b>Staff Profile</b>`,
  "admin-profile-first-shift": `✨ <b>FIRST SHIFT TODAY</b> 📸\n\n`,
  "admin-profile-candidate-title": `👤 <b>Candidate Profile</b>`,
  "admin-profile-name": `👤 Name:`,
  "admin-profile-phone": `📞 Phone:`,
  "admin-profile-locations": `📍 Locations:`,
  "admin-profile-age": `🎂 Age:`,
  "admin-profile-city": `🏙️ City:`,
  "admin-profile-source": `🔍 Source:`,
  "admin-profile-appearance": `🎀 Appearance:`,
  "admin-profile-status": `📊 Status:`,
  "admin-profile-interview-time": `🗓️ Interview Time:`,
  "admin-profile-telegram": `📞 Telegram:`,
  "admin-profile-meet-interview": `📹 Meet (Interview):`,
  "admin-profile-meet-training": `📹 Meet (Training):`,
  "admin-profile-staging-date": `🗓️ Staging Date:`,
  "admin-profile-decision-hr": `⚖️ HR Decision:`,
  "admin-profile-notification-sent": `📧 Broadcast:`,
  "admin-profile-notification-status-sent": `Sent ✅`,
  "admin-profile-notification-status-pending": `Pending (6h wait) ⏳`,
  "admin-profile-decision-accepted": `ACCEPTED 🎉`,
  "admin-profile-decision-rejected": `REJECTED ❌`,
  "admin-sync-start": `⏳ Starting sync (Team + Schedule)...`,
  "admin-sync-complete": (p: { created: string | number, updated: string | number, count: string | number }) => `✅ Sync complete!\n👥 Team: +${p.created} new, ${p.updated} updated.\n📅 Schedule: +${p.count} shifts added.`,
  "admin-sync-enter-sheet": `Enter Google Sheet name: 📋`,
  "admin-bday-scan-start": `🎂 Scanning birthdays...`,
  "admin-bday-check-complete": `✅ Check complete.`,
  "admin-bday-menu-title": `🎂 <b>Birthdays</b>`,
  "admin-bday-select-month": `Select month:`,
  "admin-bday-btn-all-months": `📋 All Months`,
  "admin-bday-no-birthdays": (p: { monthName: string | number }) => `📭 No birthdays in ${p.monthName}.`,
  "admin-bday-no-staff": `📭 No staff with birth dates.`,
  "admin-bday-header-month": (p: { monthName: string | number }) => `🎂 <b>Birthdays — ${p.monthName}</b>`,
  "admin-bday-header-all": `🎂 <b>Birthdays</b>`,
  "month-1": "January",
  "month-2": "February",
  "month-3": "March",
  "month-4": "April",
  "month-5": "May",
  "month-6": "June",
  "month-7": "July",
  "month-8": "August",
  "month-9": "September",
  "month-10": "October",
  "month-11": "November",
  "month-12": "December",
  "admin-history-only-super-admin": `⛔️ Main Admin only`,
  "admin-timeline-history-caption": `📜 Full User History`,
  "admin-finance-balances": `💰 Balances`,
  "admin-finance-report": `📊 Report & Sync`,
  "admin-finance-sync-dds": `🔄 Sync DDS`,
  "admin-finance-audit": `⚖️ Audit`,
  "admin-finance-statement": `📋 7-day Statement`,
  "admin-finance-collecting": `⏳ Collecting data...`,
  "admin-finance-gen-statement": (p: { fopKey: string | number }) => `⏳ Generating statement (${p.fopKey})...`,
  "admin-finance-audit-running": (p: { date: string | number }) => `⏳ Running FOP audit for ${p.date}...`,
  "admin-finance-syncing-dds": (p: { date: string | number }) => `⏳ Syncing DDS for ${p.date}...`,
  "admin-audit-ask-msg": (p: { location: string, date: string, type: string, diff: string }) =>
    `🌸 Привіт!
⚠️ <b>Потрібне уточнення по фінансах</b>

` +
    `Локація: <b>${p.location}</b>
` +
    `Дата: <b>${p.date}</b>
` +
    `Тип: <b>${p.type}</b>
` +
    `Нестача: <b>${p.diff} грн</b>

` +
    `Ти не вказала коментар у таблиці. Чому виникла така розбіжність? 🙏`,
  "admin-audit-ask-success": (p: { names: string, location: string, date: string }) => `✅ Asked <b>${p.names}</b> about mismatch at <b>${p.location}</b> (${p.date}).`,
  "admin-stats-general": `📊 Statistics`,
  "admin-stats-by-city": `🏙️ Cities`,
  "admin-stats-select-city": `📊 <b>Select City:</b>`,
  "admin-stats-no-data": `No data found`,
  "admin-sys-tasks": `📋 Tasks Dashboard`,
  "admin-sys-broadcast": `📢 Broadcasts`,
  "admin-sys-tickets": `🎫 Support Tickets`,
  "admin-sys-back": `⬅️ Back`,
  "admin-sys-err-tasks": (p: { error: string | number }) => `❌ Dashboard error: ${p.error}`,
  "admin-tasks-title": (p: { date: string | number }) => `📝 <b>Tasks Dashboard | ${p.date}</b>`,
  "admin-tasks-no-tasks": `📭 No tasks for this date.`,
  "admin-tasks-urgent": `\n🚨 <b>URGENT:</b>\n`,
  "admin-tasks-loc-unknown": `Not set`,
  "admin-tasks-next": `Next ➡️`,
  "admin-tasks-history": `📂 History`,
  "admin-tasks-new": `➕ New Task`,
  "admin-tasks-details-title": `📋 <b>Task Details</b>`,
  "admin-tasks-whom": (p: { name: string | number }) => `👤 <b>To:</b> ${p.name}`,
  "admin-tasks-date": (p: { date: string | number, deadline: string | number }) => `📅 <b>Date:</b> ${p.date}${p.deadline}`,
  "admin-tasks-date-soon": `Next shift`,
  "admin-tasks-city": (p: { city: string | number }) => `🏙️ <b>City:</b> ${p.city}`,
  "admin-tasks-location": (p: { location: string | number }) => `📍 <b>Location:</b> ${p.location}`,
  "admin-tasks-text": (p: { text: string | number }) => `📝 <b>Text:</b>\n> ${p.text}`,
  "admin-tasks-has-file": `📎 <b>Has attachment</b>`,
  "admin-tasks-status-label": (p: { status: string | number }) => `📊 <b>Status:</b> ${p.status}`,
  "admin-tasks-status-done": `✅ Completed`,
  "admin-tasks-status-pending": `⏳ Pending`,
  "admin-tasks-btn-toggle": `🔄 Toggle Status`,
  "admin-tasks-btn-view-file": `📂 View Attachment`,
  "admin-tasks-btn-msg-staff": `✉️ Message Staff`,
  "admin-tasks-btn-delete": `🗑 Delete Task`,
  "admin-tasks-btn-back-list": `⬅️ Back to List`,
  "admin-tasks-ans-not-found": `❌ Task not found`,
  "admin-tasks-ans-toggled": `Status updated`,
  "admin-tasks-del-conf": `❓ <b>Delete this task?</b>`,
  "admin-tasks-del-yes": `✅ Yes, delete`,
  "admin-tasks-del-no": `❌ Cancel`,
  "admin-tasks-ans-deleted": `✅ Task deleted`,
  "admin-tasks-calendar-title": `📂 <b>Select date to view tasks:</b>`,
  "hr-hub-title": `🚀 <b>HR Hub</b>`,
  "mentor-hub-title": `🎓 <b>Mentor Hub</b>`,
  "hr-error-generic": (p: { error: string | number }) => `❌ Error: ${p.error}`,
  "support-btn-go-to-topic": "➡️ Go to topic",
  "hr-menu-back": `⬅️ Back`,
  "admin-err-insufficient-perms": `❌ Insufficient permissions.`,
  "admin-prompt-number": `Enter a number. 🔢`,
  "admin-success-need-updated": (p: { count: string | number }) => `✅ Location need updated: ${p.count}`,
  "admin-success-city-updated": (p: { city: string | number }) => `✅ City changed to: ${p.city}`,
  "admin-success-date-saved": (p: { date: string | number }) => `✅ First shift date saved: ${p.date}`,
  "admin-success-time-updated": (p: { time: string | number }) => `✅ Staging time changed to: ${p.time}`,
  "admin-topic-ans-closed": `✅ Topic closed`,
  "admin-topic-ans-fwd-ok": `✅ Forwarded to Kuznetsov`,
  "admin-topic-btn-fwd": `📩 Fwd to Kuznetsov`,
  "admin-topic-btn-close": `❌ Close Topic`,
  "admin-topic-info-outgoing": `<i>Outgoing message from Admin</i>`,
  "admin-err-super-admin-only": `⛔️ Main Admin only`,
  "btn-back": `⬅️ Back`,
  "btn-cancel": `❌ Cancel`,
  "broadcast-sent-count": (p: { count: string | number }) => `✅ Broadcast sent to ${p.count} recipients!`,
  "admin-pref-stats-err-not-found": `❌ No active preference broadcast found.`,
  "admin-pref-stats-title": `📊 <b>Schedule Preferences Status</b>`,
  "admin-pref-stats-date": (p: { date: string | number }) => `📅 Broadcast Date: <b>${p.date}</b>`,
  "admin-pref-stats-confirmed": (p: { count: string | number }) => `✅ <b>CONFIRMED (${p.count}):</b>`,
  "admin-pref-stats-declined": (p: { count: string | number }) => `🚫 <b>DECLINED (${p.count}):</b>`,
  "admin-pref-stats-pending": (p: { count: string | number }) => `⏳ <b>PENDING (${p.count}):</b>`,
  "admin-pref-stats-none": `<i>none yet</i>`,
  "admin-pref-stats-all-filled": `<i>all filled! 🎉</i>`,
  "admin-shifts-none": `📭 No shifts found for this day.`,
  "admin-schedule-gaps": `🔍 Find Gaps`,
  "admin-schedule-gaps-title": `⚠️ <b>Schedule Gaps (Next 7 Days):</b>`,
  "admin-schedule-gaps-empty": `✅ <b>No gaps found for the next week!</b>\nAll locations are covered. ✨`,
  "admin-schedule-gaps-footer": `\n<i>Please find photographers for these slots urgently!</i> 🚀`,
  "admin-schedule-select-date": `📅 <b>Select Date:</b>`,
  "admin-schedule-history": `🔙 History`,
  "admin-schedule-history-title": `📅 <b>Past 7 Days</b>`,
  "admin-staff-none-loc": `📭 Staff not assigned.`,
  "support-btn-force-close": `🔒 Force Close`,
  "hr-error-overlap": `✨ This time slot is already occupied. Please choose another window. 📅`
};
